### ISSUE TITLE
AttributeError: module 'pipe' has no attribute '__all__'

### ISSUE THREAD

**Issue by dyangny** [sspipe/sspipe#13] opened 2022-05-24 06:13 UTC
`from sspipe import p, px`
throws the error:
`AttributeError: module 'pipe' has no attribute '__all__'`

**Comment by ringeringeraja** [comment] 2022-05-25 02:02
I solved it downgrading the "pipe" dependency to version 1.6.0.

**Comment by mohammad7t** [comment] 2022-05-29 03:45
Thanks for reporting the dependency issue. The issue is fixed in sspipe>=0.1.17.

**Closed by mohammad7t** 2022-05-29 03:45 UTC
